; Heat Dweller Configuration File
; This file contains various settings for the Heat Dweller experience. You can edit these settings to customize your gameplay experience. Make sure to save the file after making any changes.
; 0 is disabled, 1 is enabled

DebugConsoleEnabled=0